"""Config loading and AES-256-CBC decryption.

Replicates the encryption scheme from backend/utils.py so the agent can
read the secureconfig.json generated by the console.
"""

import base64
import hashlib
import json
import logging
import os
import sys

from Crypto.Cipher import AES
from Crypto.Util.Padding import unpad

logger = logging.getLogger("browser_guardian_agent")

# Must match backend/utils.py line 47
_MASTER_KEY = os.getenv("ENCRYPTION_MASTER_KEY", "BrowserGuardian2024!MasterKey").encode()
_AES_KEY = hashlib.sha256(_MASTER_KEY).digest()  # 32-byte key for AES-256

# Default config values
DEFAULTS = {
    "server_url": "http://localhost:8000",
    "collection_interval_minutes": 5,
    "max_history_days": 30,
    "monitored_start_time": "08:00",
    "monitored_end_time": "23:59",
    "enable_chrome": True,
    "enable_edge": True,
    "log_max_mb": 10,
    "log_roll_count": 3,
}


def _get_base_dir() -> str:
    """Return the directory containing the .exe (frozen) or this .py file."""
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


def decrypt_secure_config(encrypted_config: dict) -> dict:
    """Decrypt secureconfig.json payload. Mirrors backend/utils.py:78-121."""
    encrypted_data = base64.b64decode(encrypted_config["encrypted_data"])
    iv = base64.b64decode(encrypted_config["iv"])
    expected_checksum = encrypted_config["checksum"]

    cipher = AES.new(_AES_KEY, AES.MODE_CBC, iv)
    raw_bytes = unpad(cipher.decrypt(encrypted_data), AES.block_size)

    actual_checksum = hashlib.sha256(raw_bytes).hexdigest()
    if actual_checksum != expected_checksum:
        raise ValueError(f"Config checksum mismatch: {actual_checksum} != {expected_checksum}")

    return json.loads(raw_bytes.decode("utf-8"))


def load_config() -> dict:
    """Load and decrypt secureconfig.json from the agent's directory.

    Falls back to defaults if the file is missing or decryption fails.
    """
    config_path = os.path.join(_get_base_dir(), "secureconfig.json")

    if not os.path.isfile(config_path):
        logger.warning("secureconfig.json not found at %s, using defaults", config_path)
        return dict(DEFAULTS)

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            encrypted = json.load(f)
        config = decrypt_secure_config(encrypted)
        logger.info("Config loaded and decrypted successfully")
        # Merge with defaults for any missing keys
        merged = dict(DEFAULTS)
        merged.update(config)
        return merged
    except Exception as e:
        logger.error("Failed to load config: %s — using defaults", e)
        return dict(DEFAULTS)
